/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.testgame;
import static com.sun.corba.se.impl.naming.cosnaming.TransientNameServer.trace;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.FileWriter;
import static java.lang.System.out;
import javax.swing.ButtonGroup;
import javax.swing.Icon;
/**
 *
 * @author Andrew
 */
public class NewGame extends javax.swing.JFrame {
    String playerName;
    String playerPassword;
    String nameAndPassword;
    double g=9.81;
    private String backgroundName = "backdrop.png";
    private boolean Trace = true;
    private int turnTime = 10;
    private int gameTime = 600;
    
    
    private Panel1 backdrop;
    /**
     * Creates new form NewGame
     */
    public NewGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("checked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        nameField = new javax.swing.JTextField();
        playerField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Backdropbutton1 = new javax.swing.JRadioButton();
        Backdropbutton2 = new javax.swing.JRadioButton();
        Backdropbutton3 = new javax.swing.JRadioButton();
        Backdropbutton4 = new javax.swing.JRadioButton();
        settingsButton = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(getIconImages());

        nameField.setText("Player1");
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        playerField.setText("1234");

        jLabel2.setText("Payer Name");

        jLabel1.setText("Password");

        jButton1.setBackground(new java.awt.Color(0, 255, 0));
        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Backdropbutton1.setText("Back Drop 1");
        Backdropbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Backdropbutton1ActionPerformed(evt);
            }
        });

        Backdropbutton2.setText("Back Drop 2");

        Backdropbutton3.setText("Back Drop 3");
        Backdropbutton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Backdropbutton3ActionPerformed(evt);
            }
        });

        Backdropbutton4.setText("Back Drop 4");

        settingsButton.setText("Settings");
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Backdropbutton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Backdropbutton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Backdropbutton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Backdropbutton4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 120, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                    .addContainerGap())
                                .addComponent(nameField)
                                .addComponent(playerField))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Backdropbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Backdropbutton2)
                    .addComponent(Backdropbutton3)
                    .addComponent(Backdropbutton4))
                .addGap(18, 18, 18)
                .addComponent(settingsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String settings1=String.valueOf(g);
        String settings2=String.valueOf(Trace);
        String settings3=String.valueOf(turnTime);
        String settings4=String.valueOf(gameTime);


        playerName = nameField.getText()+".txt";
        playerPassword = playerField.getText();
        System.out.println(playerName);
        nameAndPassword = (playerName+" "+playerPassword);
        System.out.println(g);
        
        

        String fileName = playerName;
        if(Backdropbutton1.isSelected())
        {
            
        }
        else if(Backdropbutton2.isSelected())
        {
            
        }
        else if(Backdropbutton3.isSelected())
        {
            
        }
        else if(Backdropbutton4.isSelected())
        {
            
        }
        else 
        {
            
        }
        FileWriter writer = null;
        try {
            writer = new FileWriter(fileName);
            nameField.write(writer);
            playerField.write(writer);
            String mainString= " "+settings1+" "+ settings2+" "+settings3+" "+settings1;
            //writer.write("Gravity= ");
            writer.write(mainString);
            
        } catch (IOException ex) {
            Logger.getLogger(NewGame.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            if (writer!=null){
                try {
                    writer.close();
                } catch (IOException ex) {
                    Logger.getLogger(NewGame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
        String[] args={};
        TestGame.main(args);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Backdropbutton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Backdropbutton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Backdropbutton3ActionPerformed

    private void Backdropbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Backdropbutton1ActionPerformed
        Icon image = null;
        Panel1.setIcon(image);
    }//GEN-LAST:event_Backdropbutton1ActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        String[] args={};
        SettingsFrame.main(args);
        SettingsMenu mySettings;
        mySettings= new SettingsMenu();
        g = mySettings.getGravity();
        turnTime= mySettings.getMaxTurnTime();
        Trace= mySettings.setTraceShot(Trace);
        gameTime= mySettings.getMaxGameTime();
        
        
        /*
        
         private String backgroundName = "backdrop.png";
    private boolean Trace = true;
    private int turnTime = 10;
    private int gameTime = 600;
        */
        
    }//GEN-LAST:event_settingsButtonActionPerformed

    private void groupButton( ) {

ButtonGroup bg1 = new ButtonGroup( );

bg1.add(Backdropbutton1);
bg1.add(Backdropbutton2);
bg1.add(Backdropbutton3);
bg1.add(Backdropbutton4);



}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Backdropbutton1;
    private javax.swing.JRadioButton Backdropbutton2;
    private javax.swing.JRadioButton Backdropbutton3;
    private javax.swing.JRadioButton Backdropbutton4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField playerField;
    private javax.swing.JButton settingsButton;
    // End of variables declaration//GEN-END:variables
}
