// PROJECT: Archer -- a game developed for CS 321
package edu.archer;

/**
 *
 * @author jonsh_000
 */
public class PracticeMenu extends javax.swing.JFrame {

   
    
    private Archer game;
    
    /** Reference to the settings menu. */
    private SettingsMenu settings;
    
    /**
     * Creates new form PracticeMenu
     */
    public PracticeMenu(Archer game) 
    {
        initComponents();
        this.game = game;
	settings = SettingsMenu.GetSettings();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                P1NameField = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                P1Character = new javax.swing.JComboBox<>();
                jLabel3 = new javax.swing.JLabel();
                P1Weapon = new javax.swing.JComboBox<>();
                PracticeButton = new javax.swing.JButton();
                P1TextField = new javax.swing.JTextField();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                P1NameField.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
                P1NameField.setText("Player1 Name:");

                jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
                jLabel2.setText("P1 Character:");

                P1Character.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
                P1Character.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Stick Guy", "Hat Guy" }));
                P1Character.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                P1CharacterActionPerformed(evt);
                        }
                });

                jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
                jLabel3.setText("P1 Weapon:");

                P1Weapon.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
                P1Weapon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bow", "Rock", "Laser", "Trident" }));
                P1Weapon.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                P1WeaponActionPerformed(evt);
                        }
                });

                PracticeButton.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
                PracticeButton.setText("Practice");
                PracticeButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                PracticeButtonActionPerformed(evt);
                        }
                });

                P1TextField.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
                P1TextField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                P1TextFieldActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(P1NameField)
                                                .addGap(18, 18, 18)
                                                .addComponent(P1TextField))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel3))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(P1Character, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(P1Weapon, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 58, Short.MAX_VALUE)))))
                                .addGap(85, 85, 85))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addComponent(PracticeButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(P1NameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(P1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                                        .addComponent(P1Character, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(P1Weapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(174, 174, 174)
                                .addComponent(PracticeButton)
                                .addGap(118, 118, 118))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void P1CharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P1CharacterActionPerformed
        // TODO add your handling code here:

        //get the character for P1 that the user had selected at the time
        int temp = P1Character.getSelectedIndex();
        settings.setP1Character(temp);
    }//GEN-LAST:event_P1CharacterActionPerformed

    private void P1WeaponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P1WeaponActionPerformed
        // TODO add your handling code here:

        //get the weapon for P2 that the user had selected at the time
        int temp = P1Weapon.getSelectedIndex();
        settings.setP1Weapon(temp);
    }//GEN-LAST:event_P1WeaponActionPerformed

    private void PracticeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PracticeButtonActionPerformed
        // TODO add your handling code here:

        //start the game
        String player1 = P1TextField.getText();
	game.setUpGame(player1,
		"Target",
		P1Character.getSelectedIndex()+1,
                1,
		Projectile.Type.values()[P1Weapon.getSelectedIndex()],
		Projectile.Type.values()[0],
		true);
	this.setVisible(false);
    }//GEN-LAST:event_PracticeButtonActionPerformed

    private void P1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P1TextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PracticeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PracticeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PracticeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PracticeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new PracticeMenu().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JComboBox<String> P1Character;
        private javax.swing.JLabel P1NameField;
        private javax.swing.JTextField P1TextField;
        private javax.swing.JComboBox<String> P1Weapon;
        private javax.swing.JButton PracticeButton;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        // End of variables declaration//GEN-END:variables
}
